version: "3"

networks:
  proxy:
    external: true
  internal:

services:
  traefik:
    container_name: traefik
    image: traefik:1.7.4-alpine
    restart: always
    depends_on:
      - web
    command: --docker
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:monitor.oymt.xyz
      - traefik.port=8080
    networks:
      - proxy
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json

  web:
    container_name: web
    image: nginx:1.15.7-alpine
    restart: always
    labels:
      - traefik.backend=web
      - traefik.frontend.rule=Host:oymt.xyz
      - traefik.port=80
    networks:
      - internal
    depends_on:
      - php
      - database
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/app:/usr/share/nginx/html

  database:
    container_name: database
    image: mariadb:10.4.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    networks:
      - internal
    labels:
      - traefik.enable=false
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - database
    labels:
      - traefik.backend=phpmyadmin
      - traefik.frontend.rule=Host:pma.oymt.xyz
      - traefik.port=80
    networks:
      - internal
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_PORT=3306
    volumes:
      - /sessions

  php:
    container_name: php
    image: php:7.3-fpm-alpine
    restart: always
    networks:
      - internal
    labels:
      - traefik.enable=false
    volumes:
      - $PWD/app:/var/www/html
