debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[retry]
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "oymt.xyz"
watch = true
exposedByDefault = false
[acme]
email = "omermutlu29@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[web]
address = ":8080"

  [acme.httpChallenge]
    entryPoint = "http"
[[acme.domais]]
  main = "oymt.xyz"
  sans = ["monitor.oymt.xyz", "oymt.xyz"]
